version: '3.3'                 # docker-composeのversionを指定
services:
  db:
    build: ./docker/mysql       # Dockerfileの置き場所を指定
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3314:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  python3:
    restart: always
    build: ./docker/python
    container_name: 'python3'
    working_dir: '/var/www/html'
    tty: true
    environment:
      TW_CONSUMER_KEY: ${TW_CONSUMER_KEY}
      TW_CONSUMER_SECRET: ${TW_CONSUMER_SECRET}
      TW_ACCESS_TOKEN: ${TW_ACCESS_TOKEN}
      TW_ACCESS_TOKEN_SECRET: ${TW_ACCESS_TOKEN_SECRET}
    volumes:
      - ${SRC_PATH}:/var/www/html
